### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by zapat3ro** [polkaulfield/spotify_flatpak_remove_pocasts#2]
As of April 28, 2022 spotify flatpak shows podcasts (Episodes For You section) again :-( I am running Fedora 35 up-to-date, nothing particularly custom. I ran the script again when I noticed podcasts showing up (closed Spotify first ofc), and they are still there. Haven't rebooted to test, but it may some new "feature" of the client?
Not super well-versed in how to report these issues, but happy to run tests if you let me know what you need.
Thanks!

**Comment by zapat3ro** [comment]
After updating today it works again! Hope this can deleted/archived :-)

**Comment by HugLifeTiZ** [comment]
Actually, this isn't working for me any more, either.
